AgriFrontEnd/AgricultureFrontEnd/Controllers/ShowDataController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace AgricultureFrontEnd.Controllers;

[Authorize(Roles = "Admin")]
public class ShowDataController : Controller
{
    private readonly HttpClient _httpClient;

    public ShowDataController(HttpClient httpClient)
    {
        _httpClient = httpClient;
        _httpClient.BaseAddress = new Uri("https://localhost:7197/");
    }

    public async Task<IActionResult> AllTrees()
    {
        var response = await _httpClient.GetFromJsonAsync<List<TreeReadVM>>("Tree/GetAll");
        return View(response);
    }

    public async Task<IActionResult> AllLocations()
    {
        var response = await _httpClient.GetFromJsonAsync<List<LocationNameReadVM>>("Location/GetAll");
        return View(response);
    }

    
    [HttpGet]
    public async Task<IActionResult> DeleteTree(int id)
    {
        var response = await _httpClient.DeleteAsync($"Tree/Delete/{id}");

        if (response.IsSuccessStatusCode)
        {
            TempData["Success"] = "Tree deleted successfully.";
        }
        else
        {
            TempData["Error"] = "Failed to delete tree.";
        }

        return RedirectToAction("AllTrees");
    }

   
    [HttpGet]
    public async Task<IActionResult> DeleteLocation(int id)
    {
        var response = await _httpClient.DeleteAsync($"Location/Delete/{id}");

        if (response.IsSuccessStatusCode)
        {
            TempData["Success"] = "Location deleted successfully.";
        }
        else
        {
            TempData["Error"] = "Failed to delete location.";
        }

        return RedirectToAction("AllLocations");
    }
}

AgriFrontEnd/AgricultureFrontEnd/Views/ShowData/AllLocations.cshtml
@model  List<LocationNameReadVM>

@{
    ViewBag.Title = " Show All Trees";
    Layout = "_Layout";
}


<h3 class="mb-4 text-center">All Trees</h3>

@if (!Model.Any())
{
    <div class="alert alert-warning text-center">
        No Trees Found.
    </div>
}
else
{
    <div class="table-responsive">
        <table class="table table-hover table-bordered align-middle text-center shadow-sm" >
            <thead  style="background-color: #14ae64">
            <tr style="color: white">
                <th>Tree Name</th>
                <th>Tree Type</th>
                <th>Delete Tree</th>
               
            </tr>
            </thead>
            <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.Name</td>
                    <td>@item.LocationType</td>
                   
                    <td>
                        <a asp-controller="ShowData"
                           asp-action="DeleteLocation"
                           asp-route-id="@item.Id"
                           class="btn btn-danger"
                           onclick="return confirm('Are you sure you want to delete the Location: @item.Name?');">
                            حذف العنوان
                        </a>

                    </td>
                   
                </tr>
            }
            </tbody>
        </table>

        
        
    </div>

}

AgriFrontEnd/AgricultureFrontEnd/Views/ShowData/AllTrees.cshtml
@model  List<TreeReadVM>

@{
    ViewBag.Title = " Show All Trees";
    Layout = "_Layout";
}


<h3 class="mb-4 text-center">All Trees</h3>

@if (!Model.Any())
{
    <div class="alert alert-warning text-center">
        No Trees Found.
    </div>
}
else
{
    <div class="table-responsive">
        <table class="table table-hover table-bordered align-middle text-center shadow-sm" >
            <thead  style="background-color: #14ae64">
            <tr style="color: white">
                <th>Tree Name</th>
                <th>Tree Type</th>
                <th>Delete Tree</th>
               
            </tr>
            </thead>
            <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.Name</td>
                    <td>@item.Type</td>
                   
                    <td>
                        <a asp-controller="ShowData"
                           asp-action="DeleteTree"
                           asp-route-id="@item.Id"
                           class="btn btn-danger"
                           onclick="return confirm('Are you sure you want to delete the Tree: @item.Name?');">
                            حذف الشجرة
                        </a>

                    </td>
                   
                </tr>
            }
            </tbody>
        </table>

        
        
    </div>

}