AgriFrontEnd/AgricultureFrontEnd/Controllers/AddPlantController.cs
using AgricultureFrontEnd.Models.Vm.AfforestationVM;
using AgricultureFrontEnd.Models.Vm.TreeVm;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace AgricultureFrontEnd.Controllers;

[Authorize(Roles = "User")]
public class AddPlantController : Controller
{
    private readonly HttpClient _httpClient;

    public AddPlantController(HttpClient httpClient)
    {
        _httpClient = httpClient;
        _httpClient.BaseAddress = new Uri("https://localhost:7197/");
    }

    public async Task<IActionResult> Create()
    {
        var treeNames = await _httpClient.GetFromJsonAsync<List<TreeReadVM>>("Tree/GetAll");
        var locationNames = await _httpClient.GetFromJsonAsync<List<LocationNameReadVM>>("Location/GetAll");

        var formVM = new AfforestationFormVM
        {
            TreeNames = treeNames,
            LocationNames = locationNames
        };

        return View(formVM);
    }

    [HttpPost]
    public async Task<IActionResult> Create(AfforestationFormVM form)
    {
        
        var userIdClaim = User.Claims.FirstOrDefault(c => c.Type == "UserId");
        if (userIdClaim == null || !int.TryParse(userIdClaim.Value, out int userId))
        {
            return Unauthorized("User not logged in.");
        }

        var treeNames = await _httpClient.GetFromJsonAsync<List<TreeReadVM>>("Tree/GetAll");
        var locationNames = await _httpClient.GetFromJsonAsync<List<LocationNameReadVM>>("Location/GetAll");
        var treeTypes = await _httpClient.GetFromJsonAsync<List<TreeTypeReadVM>>("TreeType/GetAllTreeType");
        var locationTypes = await _httpClient.GetFromJsonAsync<List<LocationTypeReadVm>>("LocationType/GetAll");

        var selectedTree = treeNames.FirstOrDefault(t => t.Id == form.TreeNameId);
        var selectedLocation = locationNames.FirstOrDefault(l => l.Id == form.LocationNameId);

        if (selectedTree == null || selectedLocation == null)
        {
            ModelState.AddModelError("", "Invalid selection of tree or location.");
            form.TreeNames = treeNames;
            form.LocationNames = locationNames;
            return View(form);
        }

        var selectedTreeType = treeTypes.FirstOrDefault(t =>
            t.Type.Trim().ToLower() == selectedTree.Type?.Trim().ToLower());

        var selectedLocationType = locationTypes.FirstOrDefault(l =>
            l.LocationType.Trim().ToLower() == selectedLocation.LocationType?.Trim().ToLower());

        var sendData = new AfforestationAddVM
        {
            TreeNameId = form.TreeNameId,
            TreeTypeId = selectedTreeType?.Id ?? 0,
            LocationNameId = form.LocationNameId,
            LocationTypeId = selectedLocationType?.Id ?? 0,
            Number = form.Number,
            DateOfPlanted = DateOnly.FromDateTime(form.DateOfPlanted),
            UserId = userId 
        };

        await _httpClient.PostAsJsonAsync("api/afforestation/Add", sendData);

        return RedirectToAction("Success");
    }

    public IActionResult Success()
    {
        return View();
    }
}

AgriFrontEnd/AgricultureFrontEnd/Controllers/HomeController.cs
using Microsoft.AspNetCore.Authorization;

namespace AgricultureFrontEnd.Controllers;

[Authorize]
public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        var role = User.FindFirst(System.Security.Claims.ClaimTypes.Role)?.Value;
        ViewBag.Role = role; 
        return View();
    }
}

AgriFrontEnd/AgricultureFrontEnd/Controllers/RegisterController.cs
using Microsoft.AspNetCore.Authorization;

namespace AgricultureFrontEnd.Controllers;
[Authorize(Roles = "Admin")]
public class RegisterController : Controller
{
    private readonly HttpClient _client;

    public RegisterController(HttpClient client)
    {
        _client = client;
        _client.BaseAddress = new Uri("https://localhost:7197/");
    }
    
    [HttpGet]
    public IActionResult Register()
    {
        return View();
    }
    [HttpPost]
    public async Task<IActionResult> Register(RegisterVM model)
    {
        await _client.PostAsJsonAsync("User/Register/register", model);
        return RedirectToAction(nameof(Success));
    }
    
    public IActionResult Success()
    {
        return View();
    }
}

AgriFrontEnd/AgricultureFrontEnd/Controllers/SearchController.cs
using AgricultureFrontEnd.Models.Vm.AfforestationVM;
using AgricultureFrontEnd.Models.Vm.UsersVM;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Net.Http.Json;

namespace AgricultureFrontEnd.Controllers
{
    [Authorize(Roles = "Admin,Viewer")]
 
    public class SearchController : Controller
    {
        private readonly HttpClient _client;

        public SearchController(HttpClient client)
        {
            _client = client;
            _client.BaseAddress = new Uri("https://localhost:7197/");
        }

        [HttpGet]
        public async Task<IActionResult> GetStatistics()
        {
            var model = new AfforestationSearchVM
            {
                Users = await LoadUsersAsync(),
                Locations = await LoadLocationsAsync(),
                Trees = await LoadTreesAsync()
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> GetStatistics(AfforestationSearchVM model)
        {
            model.Users = await LoadUsersAsync();
            model.Locations = await LoadLocationsAsync();
            model.Trees = await LoadTreesAsync();

            if (model.FromDate == null || model.ToDate == null)
            {
                ModelState.AddModelError("", "Please select both dates.");
                return View(model);  
            }

            var response = await _client.PostAsJsonAsync("api/afforestation/search", model);

            if (!response.IsSuccessStatusCode)
            {
                ModelState.AddModelError("", "Server error, please try again later.");
                return View(model);
            }

            var result = await response.Content.ReadFromJsonAsync<List<AfforestationReadVM>>();

            var summaries = result.GroupBy(a => a.TreeName)
                .Select(t => new TreeSummaryReadVM
                {
                    TreeName = t.Key,
                    TotalPlanted = t.Sum(a => a.Number),
                }).ToList();

            var page = new AfforestationPageVM
            {
                TreeDetails = result,
                TreeSummaries = summaries
            };

            return View("SearchResults", page);
        }

        private async Task<List<SelectListItem>> LoadUsersAsync()
        {
            var users = await _client.GetFromJsonAsync<List<UserReadVM>>("User/GetAll");

            
            var normalUsers = users
                .Where(u => u.Role == Roles.User)
                .Select(u => new SelectListItem
                {
                    Value = u.Id.ToString(),
                    Text = u.Name
                }).ToList();

            normalUsers.Insert(0, new SelectListItem { Value = "", Text = "All Users" });

            return normalUsers;
        }

        private async Task<List<SelectListItem>> LoadLocationsAsync()
        {
            var locations = await _client.GetFromJsonAsync<List<LocationNameReadVM>>("Location/GetAll");
            var items = locations.Select(l => new SelectListItem { Value = l.Id.ToString(), Text = l.Name }).ToList();
            items.Insert(0, new SelectListItem { Value = "", Text = "All Locations" });
            return items;
        }

        private async Task<List<SelectListItem>> LoadTreesAsync()
        {
            var trees = await _client.GetFromJsonAsync<List<TreeReadVM>>("Tree/GetAll");
            var items = trees.Select(t => new SelectListItem { Value = t.Id.ToString(), Text = t.Name }).ToList();
            items.Insert(0, new SelectListItem { Value = "", Text = "All Trees" });
            return items;
        }
    }
}

AgriFrontEnd/AgricultureFrontEnd/Controllers/UsersController.cs
using Microsoft.AspNetCore.Mvc;
using AgricultureFrontEnd.Models.Vm.UsersVM;
using Microsoft.AspNetCore.Authorization;

[Authorize(Roles = "Admin")]
public class UsersController : Controller
{
    private readonly IHttpClientFactory _httpClientFactory;

    public UsersController(IHttpClientFactory httpClientFactory)
    {
        _httpClientFactory = httpClientFactory;
    }

    public async Task<IActionResult> ShowUsers()
    {
        using var client = _httpClientFactory.CreateClient();
        var response = await client.GetFromJsonAsync<List<UserReadVM>>(
            "https://localhost:7197/User/GetAll");

        return View(response);
    }

    public async Task<IActionResult> DeleteUser(int id)
    {
        using var client = _httpClientFactory.CreateClient();

        if (id <= 0)
        {
            TempData["Error"] = "Invalid user ID.";
            return RedirectToAction(nameof(ShowUsers));
        }

        var url = $"https://localhost:7197/User/DeleteUser/{id}";
        Console.WriteLine($"Attempting DELETE request to URL: {url}");

        var response = await client.DeleteAsync(url);

        if (!response.IsSuccessStatusCode)
        {
            TempData["Error"] = $"Failed to delete user with ID {id}.";
        }
        else
        {
            TempData["Success"] = $"User with ID {id} deleted successfully.";
        }

        return RedirectToAction(nameof(ShowUsers));
    }
}

AgriFrontEnd/AgricultureFrontEnd/Views/Home/Index.cshtml
<h2>Welcome!</h2>

@if (!User.Identity.IsAuthenticated)
{
    <p>Please <a asp-controller="Account" asp-action="Login">log in</a>.</p>
}
else
{
    <p>You are logged in as <b>@User.Identity.Name</b>.</p>

    <p>
        <a asp-controller="Account" asp-action="Logout">
            Logout
        </a>
    </p>

    @if (User.IsInRole("Admin"))
    {
        <h3>Admin Panel</h3>
        <p>Only visible to Admins.</p>
        <a asp-controller="AddNewTree" asp-action="Create" class="btn btn-success"
           style="background-color: #14ae64; box-shadow: none;">
            اضافه شجرة
        </a>

        <a asp-controller="AddNewLocation" asp-action="Create" class="btn btn-success"
           style="background-color: #14ae64;   box-shadow: none;">
            اضافه عنوان
        </a>

        <a asp-controller="Search" asp-action="GetStatistics" class="btn btn-success"
           style="background-color: #14ae64;  box-shadow: none;">
            بحث
        </a>

        <a asp-controller="Register" asp-action="Register" class="btn btn-success"
           style="background-color: #14ae64;   box-shadow: none;">
            اضافة مستخدم
        </a>

        <a asp-controller="Users" asp-action="ShowUsers" class="btn btn-success"
           style="background-color: #14ae64; ; box-shadow: none;">
            اظهار جميع المستخدمين
        </a>
        <a asp-controller="AddTreeType" asp-action="Create" class="btn btn-success"
           style="background-color: #14ae64; ; box-shadow: none;">
            اضافة نوع شجرة جديد
        </a>
        <a asp-controller="AddLocationType" asp-action="Create" class="btn btn-success"
           style="background-color: #14ae64; ; box-shadow: none;">
            اضافة نوع عنوان جديد
        </a>
        <a asp-controller="ShowData" asp-action="AllTrees" class="btn btn-success"
           style="background-color: #14ae64; ; box-shadow: none;">
            اظهار جميع الاشجار
        </a>
        <a asp-controller="ShowData" asp-action="AllLocations" class="btn btn-success"
           style="background-color: #14ae64; ; box-shadow: none;">
            اظهار جميع العناوين
        </a>

    }
    else if (User.IsInRole("User"))
    {
        <h3>User Dashboard</h3>
        <a asp-controller="AddPlant" asp-action="Create" class="btn btn-success" style="background-color: #14ae64">اضافة زراعة</a>
        
    }
    else if(User.IsInRole(nameof(Roles.Viewer)))
    {
        <h3>Viewer Dashboard</h3>
        <a asp-controller="Search" asp-action="GetStatistics" class="btn btn-success"
           style="background-color: #14ae64;  box-shadow: none;">
            بحث
        </a>
    }
}